import pytest

from tiberium_ai.source_role import (
    ROLE_SUPPRESSIONS,
    SUPPRESS_ALL,
    RoleProfile,
    SourceRole,
    classify_source_role,
    classify_source_text,
    suppressions_for,
)
from tiberium_ai.source_scan import scan_source

MODULE = '\n'.join([
    '"""A module."""',
    '',
    'import os',
    '',
    '',
    'def f():',
    '    return os.curdir',
])

RE_EXPORT = '\n'.join([
    'from .a import A',
    'from .b import B',
    '',
    '__all__ = ["A", "B"]',
])

INTERFACE = '\n'.join([
    'from typing import Protocol',
    '',
    '',
    'class Port(Protocol):',
    '    def run(self) -> None: ...',
])

SCRIPT = '\n'.join([
    '"""A program."""',
    '',
    '',
    'def main() -> int:',
    '    print("hello")',
    '    return 0',
    '',
    '',
    'if __name__ == "__main__":',
    '    raise SystemExit(main())',
])

GENERATED = '\n'.join([
    '# Code generated by a tool. Do not edit.',
    '',
    'import os',
])


def profile_of(path: str, source: str) -> RoleProfile:
    return classify_source_role(scan_source(path, source))


def test_every_role_declares_its_suppressions():
    dimensions = {
        "substance",
        "structure_integrity",
        "documentation_balance",
        "import_hygiene",
    }
    assert set(ROLE_SUPPRESSIONS) == set(SourceRole)
    for role, names in ROLE_SUPPRESSIONS.items():
        assert SUPPRESS_ALL in names or names <= dimensions, role


def test_an_ordinary_module_suppresses_nothing():
    profile = profile_of("plain.py", MODULE)

    assert profile.role is SourceRole.MODULE
    assert profile.reason_code == "module_default"
    assert profile.suppressions == ()


def test_a_package_marker_skips_two_dimensions():
    profile = profile_of("pkg/__init__.py", "")

    assert profile.role is SourceRole.PACKAGE_INIT
    assert profile.suppresses("import_hygiene")
    assert profile.suppresses("documentation_balance")
    assert not profile.suppresses("substance")


def test_a_reexport_module_skips_import_hygiene_only():
    profile = profile_of("surface.py", RE_EXPORT)

    assert profile.role is SourceRole.RE_EXPORT
    assert profile.suppressions == ("import_hygiene",)


def test_a_module_defining_a_class_is_not_a_reexport_surface():
    source = '\n'.join([
        'import os',
        'from typing import Any',
        '',
        '',
        'class Thing:',
        '    value: Any = None',
    ])
    assert profile_of("thing.py", source).role is SourceRole.MODULE


def test_an_abstract_interface_skips_substance_only():
    profile = profile_of("ports.py", INTERFACE)

    assert profile.role is SourceRole.INTERFACE
    assert profile.suppressions == ("substance",)


def test_a_main_guard_marks_a_script():
    profile = profile_of("tool.py", SCRIPT)

    assert profile.role is SourceRole.SCRIPT
    assert profile.reason_code == "main_guard"
    assert profile.suppressions == ()


def test_a_generated_header_suppresses_every_check():
    profile = profile_of("generated_pb2.py", GENERATED)

    assert profile.role is SourceRole.GENERATED
    assert profile.suppresses_everything
    assert profile.suppresses("substance")


def test_a_test_path_and_a_corpus_path_are_distinguished():
    assert profile_of("tests/test_x.py", MODULE).role is SourceRole.TEST
    assert profile_of("pkg/x_test.py", MODULE).role is SourceRole.TEST
    corpus = profile_of("tests/corpus/bad.py", MODULE)
    assert corpus.role is SourceRole.CORPUS
    assert corpus.suppresses_everything


def test_an_empty_module_is_still_an_ordinary_module():
    profile = profile_of("empty.py", "")

    assert profile.role is SourceRole.MODULE
    assert profile.reason_code == "empty_module"
    assert profile.suppressions == ()


def test_unparsable_text_keeps_no_suppression_and_says_so():
    profile = classify_source_text("broken.py", "def f(:")

    assert profile.role is SourceRole.MODULE
    assert profile.reason_code == "source_unparsable"
    assert profile.suppressions == ()
    assert not profile.suppresses_everything


def test_suppressions_are_returned_sorted():
    assert suppressions_for(SourceRole.PACKAGE_INIT) == (
        "documentation_balance",
        "import_hygiene",
    )


def test_a_role_profile_refuses_malformed_input():
    with pytest.raises(TypeError):
        RoleProfile(role="module", reason_code="x")
    with pytest.raises(ValueError):
        RoleProfile(role=SourceRole.MODULE, reason_code=" x ")
    with pytest.raises(ValueError):
        RoleProfile(role=SourceRole.MODULE, reason_code="x", suppressions=("a", "a"))


def test_suppression_lookup_refuses_a_blank_name():
    with pytest.raises(ValueError):
        RoleProfile(SourceRole.MODULE, "x").suppresses("")
