import pytest

from tiberium_ai.audit import (
    AUDIT_CAPABILITY,
    AUDIT_VERIFIER_ID,
    AuditRequest,
    audit_policy_version,
    audit_route_entry,
    audit_source,
    measure_dimensions,
    recompute_verifier,
    register_audit_verifiers,
)
from tiberium_ai.audit_store import SqliteAuditStore
from tiberium_ai.contracts import Task
from tiberium_ai.pattern_rules import builtin_rule_registry
from tiberium_ai.registry import RouteRegistry
from tiberium_ai.source_role import classify_source_text
from tiberium_ai.source_scan import scan_source
from tiberium_ai.verification import VerifierRegistry

POLICY = audit_policy_version('static-audit-v1')

CLEAN = '\n'.join([
    '"""A complete module."""',
    '',
    'import math',
    '',
    '',
    'def area(radius: float) -> float:',
    '    """Return the area of a circle."""',
    '    if radius < 0:',
    '        raise ValueError("radius must be nonnegative")',
    '    return math.pi * radius ** 2',
])

DIRTY = '\n'.join([
    '# TODO: replace this placeholder',
    'import json',
    '',
    '',
    'def declared():',
    '    """Declared but not implemented."""',
    '    pass',
    '',
    '',
    'def loaded():',
    '    try:',
    '        return json.loads("{}")',
    '    except Exception:',
    '        pass',
])


def audit(source, path='sample.py', policy_version=POLICY):
    return audit_source(AuditRequest('audit-001', path, source), policy_version=policy_version)


def test_a_complete_module_is_sound_and_reproducible():
    first = audit(CLEAN)
    second = audit(CLEAN)

    assert first.band == 'sound'
    assert first.findings_total == 0
    assert first.dimensions['substance'] == 1.0
    assert first.dimensions['import_hygiene'] == 1.0
    assert first.to_dict() == second.to_dict()


def test_a_declared_but_empty_module_scores_worse_with_named_findings():
    outcome = audit(DIRTY)

    assert outcome.band in {'noted', 'questionable'}
    assert outcome.deficit is not None and outcome.deficit > 20.0
    assert outcome.dimensions['substance'] == 0.5
    assert outcome.rule_counts == {'rule.placeholder-marker': 1, 'rule.silent-except': 1}
    assert outcome.findings_total == 2
    assert [finding.detail_code for finding in outcome.findings] == ['marker.todo', 'except.silent']


def test_the_verdict_carries_the_policy_that_produced_it():
    outcome = audit(CLEAN)

    assert outcome.policy_version == POLICY
    assert outcome.policy_version.endswith(builtin_rule_registry().fingerprint())


def test_a_stale_policy_version_is_refused():
    with pytest.raises(ValueError):
        audit(CLEAN, policy_version='static-audit-v1')


def test_an_unparsable_module_is_undetermined_rather_than_clean():
    outcome = audit('def f(:')

    assert outcome.band == 'undetermined'
    assert outcome.deficit is None
    assert outcome.reason_code == 'source_unparsable'
    assert outcome.determined is False


def test_a_role_that_suppresses_every_check_is_reported_as_unjudged():
    generated = audit('# Code generated by tooling. Do not edit.', path='models_pb2.py')
    corpus = audit(CLEAN, path='tests/corpus/sample.py')

    assert generated.reason_code == 'role_suppresses_all_checks'
    assert generated.role == 'generated'
    assert corpus.role == 'corpus'
    assert corpus.band == 'undetermined'


def stored(source, store, policy_version=POLICY, path='sample.py', registry=None):
    return audit_source(
        AuditRequest('audit-001', path, source),
        policy_version=policy_version,
        registry=registry,
        store=store,
        recorded_at='2026-09-21T00:00:00Z',
        project_id='parcimonia',
    )


def test_a_recording_call_must_supply_provenance():
    with SqliteAuditStore(':memory:') as store:
        with pytest.raises(ValueError):
            audit_source(AuditRequest('t', 'sample.py', CLEAN), policy_version=POLICY, store=store)


def test_a_second_audit_of_the_same_text_reuses_the_stored_verdict():
    with SqliteAuditStore(':memory:') as store:
        first = stored(CLEAN, store)
        second = stored(CLEAN, store)

        assert first.reused is False
        assert second.reused is True
        assert second.deficit == first.deficit
        assert second.dimensions == first.dimensions
        assert store.count() == 1


def test_a_rule_change_forces_a_new_audit_instead_of_reuse():
    narrowed = builtin_rule_registry()
    narrowed.disable('rule.placeholder-marker')
    narrowed_policy = audit_policy_version('static-audit-v1', narrowed)

    with SqliteAuditStore(':memory:') as store:
        stored(DIRTY, store)
        renamed = stored(
            DIRTY, store, policy_version=narrowed_policy, registry=narrowed
        )

        assert renamed.reused is False
        assert renamed.rule_counts == {'rule.silent-except': 1}
        assert store.count() == 2


def test_verification_recomputes_the_verdict_instead_of_trusting_it():
    outcome = audit(DIRTY)
    claim = {
        'band': outcome.band,
        'deficit': outcome.deficit,
        'content_hash': outcome.content_hash,
    }
    honest = {'source': DIRTY, 'path': 'sample.py', 'policy_version': POLICY, 'claimed': claim}
    tampered = dict(honest, claimed=dict(claim, deficit=0.0))

    assert recompute_verifier(honest) is True
    assert recompute_verifier(tampered) is False


def test_a_malformed_verification_payload_abstains_rather_than_rejecting():
    registry = VerifierRegistry()
    register_audit_verifiers(registry)

    with pytest.raises(ValueError):
        recompute_verifier({'source': CLEAN})

    verdict = registry.verify(AUDIT_VERIFIER_ID, '1', {'source': CLEAN})
    assert verdict.verdict is None
    assert verdict.detail_code == 'verifier_error:ValueError'


def test_an_undetermined_audit_never_verifies_as_accepted():
    outcome = audit('def f(:')
    payload = {
        'source': 'def f(:',
        'path': 'broken.py',
        'policy_version': POLICY,
        'claimed': {
            'band': outcome.band,
            'deficit': outcome.deficit,
            'content_hash': outcome.content_hash,
        },
    }

    assert recompute_verifier(payload) is False


def test_the_registered_verifier_accepts_a_true_verdict():
    registry = VerifierRegistry()
    register_audit_verifiers(registry)
    outcome = audit(CLEAN)
    payload = {
        'source': CLEAN,
        'path': 'sample.py',
        'policy_version': POLICY,
        'claimed': {
            'band': outcome.band,
            'deficit': outcome.deficit,
            'content_hash': outcome.content_hash,
        },
    }

    verdict = registry.verify(AUDIT_VERIFIER_ID, '1', payload)
    assert verdict.verdict is True
    with pytest.raises(ValueError):
        register_audit_verifiers(registry)


def test_a_route_manifest_cannot_invent_its_own_cost():
    with pytest.raises(TypeError):
        audit_route_entry()


def test_the_route_entry_loads_into_the_route_registry():
    verifiers = VerifierRegistry()
    register_audit_verifiers(verifiers)
    manifest = {
        'schema_version': 1,
        'registry_version': 'static-audit-v1',
        'routes': [audit_route_entry(estimated_cost=0.0, estimated_latency_ms=25.0)],
    }

    registry = RouteRegistry.from_manifest(
        manifest, known_capabilities=[AUDIT_CAPABILITY], verifiers=verifiers
    )
    task = Task('audit-001', 'audit', {})
    candidates = registry.candidates_for(task, required_capabilities=[AUDIT_CAPABILITY])

    assert registry.routes[0].route_id == 'route.audit.static'
    assert registry.routes[0].estimated_cost == 0.0
    assert [candidate.route_id for candidate in candidates] == ['route.audit.static']


def test_a_route_entry_pointing_at_an_unregistered_verifier_is_refused():
    manifest = {
        'schema_version': 1,
        'registry_version': 'static-audit-v1',
        'routes': [audit_route_entry(estimated_cost=0.0)],
    }

    with pytest.raises(ValueError):
        RouteRegistry.from_manifest(
            manifest, known_capabilities=[AUDIT_CAPABILITY], verifiers=VerifierRegistry()
        )


def test_an_audit_request_refuses_a_blank_task_id_or_path():
    with pytest.raises(ValueError):
        AuditRequest(' ', 'sample.py', CLEAN)
    with pytest.raises(ValueError):
        AuditRequest('audit-001', '', CLEAN)
    with pytest.raises(TypeError):
        AuditRequest('audit-001', 'sample.py', 3)


def test_a_package_marker_keeps_the_verdict_and_the_suppression():
    outcome = audit('import os', path='pkg/__init__.py')

    assert outcome.role == 'package_init'
    assert outcome.skipped == ('documentation_balance', 'import_hygiene')
    assert outcome.dimensions['import_hygiene'] == 1.0


def test_every_dimension_is_measured_with_its_evidence():
    scan = scan_source('sample.py', CLEAN)
    dimensions = measure_dimensions(scan, classify_source_text('sample.py', CLEAN))

    assert [item.name for item in dimensions] == [
        'substance',
        'structure_integrity',
        'documentation_balance',
        'import_hygiene',
    ]
    assert all(item.measurement for item in dimensions)
