"""Structural role of a source file, decided before anything is scored.

A package ``__init__``, a re-export module, an abstract interface and an
ordinary module do not look alike, and scoring them with one rule set produces
systematic false positives: an interface whose bodies are ``...`` has no logic
by construction, and a module that only re-exports consumes no name locally.

The classifier is therefore a filter, not a judgement. It names one role, the
reason code that produced it, and exactly which checks that role suppresses.
Every suppression is explicit, listed in :data:`ROLE_SUPPRESSIONS` and part of
the audit policy version, so relaxing a check is a visible policy change.

Failure is explicit: text that cannot be parsed keeps no suppression at all and
carries the ``source_unparsable`` reason code, so the caller abstains instead of
scoring a file whose structure is unknown.
"""

from __future__ import annotations

import ast
from dataclasses import dataclass
from enum import Enum
from pathlib import Path

from .source_scan import SourceScan, SourceScanError, scan_source

__all__ = [
    "RoleProfile",
    "SourceRole",
    "ROLE_SUPPRESSIONS",
    "SUPPRESS_ALL",
    "classify_source_role",
    "classify_source_text",
    "suppressions_for",
]

#: Wildcard used when a role suppresses every check, rules included.
SUPPRESS_ALL = "*"

_ABSTRACT_BASES = frozenset({"Protocol", "ABC", "ABCMeta"})
_GENERATED_MARKERS = (
    "generated by",
    "auto-generated",
    "autogenerated",
    "do not edit",
    "code generated",
)
_GENERATED_HEADER_LINES = 8
_CORPUS_PARTS = frozenset({"corpus", "fixtures"})
_TEST_PARTS = frozenset({"tests", "test"})
_RE_EXPORT_RATIO = 0.70


class SourceRole(str, Enum):
    """Structural role of one Python source file."""

    MODULE = "module"
    PACKAGE_INIT = "package_init"
    RE_EXPORT = "re_export"
    INTERFACE = "interface"
    SCRIPT = "script"
    TEST = "test"
    GENERATED = "generated"
    CORPUS = "corpus"


#: Checks suppressed per role. Dimension names come from ``audit_score``.
ROLE_SUPPRESSIONS: dict[SourceRole, frozenset[str]] = {
    # An ordinary module is scored on everything.
    SourceRole.MODULE: frozenset(),
    # A package ``__init__`` is a packaging convention: names are re-exported
    # rather than consumed, and a docstring-only file is normal.
    SourceRole.PACKAGE_INIT: frozenset({"import_hygiene", "documentation_balance"}),
    # A re-export module binds names for its importers by design.
    SourceRole.RE_EXPORT: frozenset({"import_hygiene"}),
    # An interface declares contracts: ``...`` bodies and ``NotImplementedError``
    # raises are the intended content, so body coverage carries no information.
    SourceRole.INTERFACE: frozenset({"substance"}),
    # A script declares itself a program entry point, so its own stdout is an
    # interface rather than leftover debris. The exception is expressed by rules
    # that do not apply to this role, not by suppressing a dimension here.
    SourceRole.SCRIPT: frozenset(),
    # Test modules are scored like modules; rules decide their own applicability.
    SourceRole.TEST: frozenset(),
    # Generated code is not authored here and its structure is not a signal.
    SourceRole.GENERATED: frozenset({SUPPRESS_ALL}),
    # Intentional negative corpora exist to be wrong.
    SourceRole.CORPUS: frozenset({SUPPRESS_ALL}),
}


@dataclass(frozen=True)
class RoleProfile:
    """One classified role, its reason code and its suppressed checks."""

    role: SourceRole
    reason_code: str
    suppressions: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        if not isinstance(self.role, SourceRole):
            raise TypeError("role must be a SourceRole.")
        if (
            not isinstance(self.reason_code, str)
            or not self.reason_code
            or self.reason_code != self.reason_code.strip()
        ):
            raise ValueError("reason_code must be a nonempty, trimmed string.")
        for name in self.suppressions:
            if not isinstance(name, str) or not name or name != name.strip():
                raise ValueError("suppression names must be nonempty, trimmed strings.")
        if len(set(self.suppressions)) != len(self.suppressions):
            raise ValueError("suppression names must not repeat.")

    def suppresses(self, name: str) -> bool:
        """Return whether this role suppresses one named check."""
        if not isinstance(name, str) or not name:
            raise ValueError("check name must be a nonempty string.")
        return SUPPRESS_ALL in self.suppressions or name in self.suppressions

    @property
    def suppresses_everything(self) -> bool:
        return SUPPRESS_ALL in self.suppressions


def suppressions_for(role: SourceRole) -> tuple[str, ...]:
    """Return the declared suppressions of ``role``, sorted and copied."""
    if not isinstance(role, SourceRole):
        raise TypeError("role must be a SourceRole.")
    return tuple(sorted(ROLE_SUPPRESSIONS[role]))


def _profile(role: SourceRole, reason_code: str) -> RoleProfile:
    return RoleProfile(role, reason_code, suppressions_for(role))


def classify_source_text(path: str, source: str) -> RoleProfile:
    """Classify text directly, keeping the fail-closed profile on a parse error."""
    try:
        return classify_source_role(scan_source(path, source))
    except SourceScanError:
        return RoleProfile(SourceRole.MODULE, "source_unparsable", ())


def classify_source_role(scan: SourceScan) -> RoleProfile:
    """Return the role of an already-scanned module.

    Detection order is fixed and documented so the same file always lands in the
    same role: generated header, intentional corpus, tests, the package marker,
    program entry point, abstract interfaces, re-export modules, and finally an
    ordinary module.
    """
    if not isinstance(scan, SourceScan):
        raise TypeError("scan must be a SourceScan.")

    parts = {part.lower() for part in Path(scan.path).parts}
    if _declares_generated(scan):
        return _profile(SourceRole.GENERATED, "generated_header")
    if parts & _CORPUS_PARTS:
        return _profile(SourceRole.CORPUS, "corpus_path")
    name = Path(scan.path).name.lower()
    if parts & _TEST_PARTS or name.startswith("test_") or name.endswith("_test.py"):
        return _profile(SourceRole.TEST, "test_path")
    if name == "__init__.py":
        return _profile(SourceRole.PACKAGE_INIT, "package_marker")

    body = scan.tree.body
    if not body:
        return _profile(SourceRole.MODULE, "empty_module")
    if _declares_script(body):
        return _profile(SourceRole.SCRIPT, "main_guard")

    classes = [node for node in body if isinstance(node, ast.ClassDef)]
    functions = [
        node for node in body if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
    ]
    if classes and not functions and all(_is_abstract_base(node) for node in classes):
        return _profile(SourceRole.INTERFACE, "abstract_interface")

    imports = sum(1 for node in body if isinstance(node, (ast.Import, ast.ImportFrom)))
    assignments = sum(
        1 for node in body if isinstance(node, (ast.Assign, ast.AugAssign, ast.AnnAssign))
    )
    # A module that defines a class is a module, not a re-export surface, even
    # when its imports dominate the top level.
    if not functions and not classes and (imports + assignments) / len(body) >= _RE_EXPORT_RATIO:
        return _profile(SourceRole.RE_EXPORT, "re_export_body")

    return _profile(SourceRole.MODULE, "module_default")


def _declares_generated(scan: SourceScan) -> bool:
    header = "\n".join(scan.source.splitlines()[:_GENERATED_HEADER_LINES]).lower()
    return any(marker in header for marker in _GENERATED_MARKERS)


def _declares_script(body: list[ast.stmt]) -> bool:
    """Return whether a module declares itself a program entry point."""
    for node in body:
        if not isinstance(node, ast.If):
            continue
        test = node.test
        if not isinstance(test, ast.Compare) or len(test.ops) != 1:
            continue
        if not isinstance(test.ops[0], ast.Eq):
            continue
        left, right = test.left, test.comparators[0]
        names = _dotted_names(left, right)
        if names == {"__name__", "__main__"}:
            return True
    return False


def _dotted_names(left: ast.AST, right: ast.AST) -> set[str]:
    found: set[str] = set()
    for node in (left, right):
        if isinstance(node, ast.Name):
            found.add(node.id)
        elif isinstance(node, ast.Constant) and isinstance(node.value, str):
            found.add(node.value)
    return found


def _is_abstract_base(node: object) -> bool:
    for base in getattr(node, "bases", ()):
        name = base.id if isinstance(base, ast.Name) else getattr(base, "attr", "")
        if name in _ABSTRACT_BASES:
            return True
    return False
